VALID_EMAIL_REGEX: '\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z'
digit_2: 2
digit_5: 5
digit_6: 6
digit_30: 30
digit_50: 50
digit_140: 140
digit_500: 500
page_10: 10
gender_male: 'Male'
gender_female: 'Female'
gender_other: 'Other'
accept_file: 'image/jpeg,image/gif,image/png,image/webp,image/jpg'
